### ISSUE TITLE
Add Lifecycle Control for Card Commands

### ISSUE THREAD

**Issue by jneander** [BluStor/GateKeeperSDK#17]
Provide timeouts where applicable. Timeouts should/must only occur when the action is guaranteed to have a null effect. Otherwise, use IOExceptions to indicate unknown state.

* [ ] Timeout
* [ ] Cancellation
* [ ] Incremental Progress Updates (if practical)

**Comment by bravozulu1** [comment]
Using GateKeeper board.  Closing
