### ISSUE TITLE
Code Design Housekeeping

### ISSUE THREAD

**Issue by jneander** [BluStor/GateKeeperSDK#19]
# Services

* [ ] unify classes
* [ ] make all AsyncTasks ServiceTasks

# GKEnvironment

* [ ] redesign for stateful (enumerated?) responsibility of Biometrics initialization, etc.
* [ ] eliminate AsyncTask and Listener
* [ ] rename to GKBiometrics
* [ ] place Faces.ndf in GateKeeper-controlled path

# GKAuthentication

* [ ] rename to GKFaceAuthentication

**Comment by bravozulu1** [comment]
Using GateKeeper board.  Closing
